import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import AppHeader from "@/widgets/AppHeader";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
		>
		<body className={'bg-background text-foreground'}>
		<Providers>
			<main className="grid grid-rows-[min-content_1fr] min-h-screen">
				<AppHeader/>
				{children}
			</main>
		</Providers>
		</body>
		</html>
	);
}
